---
- name: setup /etc/hosts on localhost
  become: yes
  lineinfile:
    regexp: '^10\..*\..*\..* {{ project }}'
    dest: /etc/hosts
    line: "{{ hostvars[project].ansible_all_ipv4_addresses[0] }} {{ project }}"
    state: present
