---
version: '2'
services:
  frontend:
    image: onelove/frontend
    volumes:
      - ./services/frontend:/usr/src/app
    command: ./bin/devel.sh
    ports:
      - "8080:8080"

  backend:
    image: python:3-onbuild
    volumes:
      - ./services/backend:/usr/src/app
      - /tmp/.cache:/root/.cache
    command: bash -c "./bin/default_user.sh && ./bin/devel.sh"
    ports:
      - "5000:5000"
    links:
      - mongodb:mongodb
      - redis:redis

  worker:
    image: python:3-onbuild
    volumes:
      - ./services/backend:/usr/src/app
      - /tmp/.cache:/root/.cache
    command: ./bin/celery_dev.sh

  redis:
    image: redis:latest

  mongodb:
    image: mongo:latest
