---
- name: install common packages
  with_items: "{{ common_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: link bash to /bin/bash
  file:
    state: link
    src: /usr/local/bin/bash
    dest: /bin/bash

- name: setup cshrc
  copy:
    src: cshrc
    dest: /root/.cshrc

- name: configure /etc/hosts
  lineinfile:
    regexp: '^127\.0\.0\.1 worker backend mongodb'
    line: '127.0.0.1 worker backend mongodb'
    dest: /etc/hosts
